id INT AUTO_INCREMENT PRIMARY KEY
name VARCHAR(255)
email VARCHAR(255) UNIQUE
phone VARCHAR(15)
address VARCHAR(255)
donation_history TEXT
user_id INT
location VARCHAR(255)
is_verified BOOLEAN DEFAULT FALSE
latitude DECIMAL(10,8)
longitude DECIMAL(11,8)